### ISSUE TITLE
Is this still up to date?

### ISSUE THREAD

**Issue by niel96** [manifoldmarkets/market-maker#3]
Dear,

i tried out this software, i'm not a programmer but trader. I got some issues at multiple occasions trying to run this software. I'm wondering if this is still up to date or doesn't work anymore? It would have been a great tool otherwise...

FetchError: invalid json response body at https://manifold.markets/api/v0/markets?limit=1000&before=KxesWYLx2QAKmkQhQh1b reason: Unexpected token 'u', "upstream c"... is not valid JSON
    at C:\Users\niel\market-maker\node_modules\node-fetch\lib\index.js:272:32
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getMarkets (C:\Users\niel\market-maker\src\api.ts:17:33)
    at async getAllMarkets (C:\Users\niel\market-maker\src\api.ts:31:35)
    at async betOnTopMarkets (C:\Users\niel\market-maker\src\market-maker.ts:43:19)
    at async main (C:\Users\niel\market-maker\src\market-maker.ts:38:5) {
  type: 'invalid-json'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

TypeError: Cannot read properties of undefined (reading 'filter')
    at C:\Users\niel\market-maker\src\market-maker.ts:59:42
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 3)
    at async batchedWaitAll (C:\Users\niel\market-maker\src\api.ts:118:19)
    at async betOnTopMarkets (C:\Users\niel\market-maker\src\market-maker.ts:56:3)
    at async main (C:\Users\niel\market-maker\src\market-maker.ts:38:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by niel96** [comment]
![ScreenHunter 1791](https://github.com/manifoldmarkets/market-maker/assets/44427841/23d47827-4d4e-474b-8c33-669eb894338e)

Ok seems like the api is not up to date anymore, hope it works now.

**Comment by jahooma** [comment]
Oh sorry, yes I haven't looked at this code in a long time

**Comment by niel96** [comment]
No problem haha. I just made some changes that i found in the pull requests. Let's see if it works now.
I have not much programming experience, first time doing this but it works with the help of chatgpt. lol

**Comment by niel96** [comment]
### I seem to still get an error:

error Command failed with exit code 1. at https://api.manifold.markets/v0/market/I9MKafdaZoi5mSMsCDmO reason: Unexpected token '<', "<!doctype "... is not valid JSON
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
C:\Users\niel\market-maker>(C:\Users\niel\market-maker\src\api.ts:10:30)
    at async C:\Users\niel\market-maker\src\market-maker.ts:59:26
    at async Promise.all (index 7)
    at async batchedWaitAll (C:\Users\niel\market-maker\src\api.ts:125:19)
    at async betOnTopMarkets (C:\Users\niel\market-maker\src\market-maker.ts:57:3)
    at async main (C:\Users\niel\market-maker\src\market-maker.ts:39:5) {
  type: 'invalid-json'
}

So seems there are now these markets that have the type: "doc". It's like just a question you can answer on. I will have to make the script skip these.

**Comment by niel96** [comment]
ok i give up, tried lot of things.
